#!/bin/sh
# postinst script for yandex-legoa-www
#
# see: dh_installdeb(1)

set -e

if [ -e /etc/yandex/environment.type ]; then
    yandex_environment=$(cat /etc/yandex/environment.type)
fi

NAME=legoa

# Setting rights and owners
chown -R www-data:www-data /var/run/yandex/${NAME}
chown -R www-data:www-data /var/log/yandex/${NAME}

nginx-enable-mod 90-${NAME}.conf
service nginx reload

#DEBHELPER#

exit 0
